title: willbeez
description: Welcome to my personal site
baseurl: ""
url: "https://willbeez.com"
markdown: kramdown
theme: jekyll-theme-primer
avatar: https://avatars.githubusercontent.com/u/3200244?v=4
plugins:
  - jekyll-feed
  - jekyll-avatar
sass:
  sass_dir: assets/css
  style: compressed
