title: Hello World Blog
description: A simple blog using GitHub Pages and Jekyll
baseurl: ""
url: "https://<your-username>.github.io/hello-world-blog"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed