title: <img src="https://avatars.githubusercontent.com/u/3200244?v=4" alt="Profile picture" width="150px" height="150px" style="border: 1px solid black; border-radius: 50%;">William Beasley
description: Welcome to my personal site
baseurl: ""
url: "https://willbeez.com"
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
